import { Helper } from './helper';
export const HELPERS: Helper[] = [
  {
    id: 1,
    name: 'Aditi Sharma',
    role: 'Cook',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    employeeCode: 'C001',
    gender: 'Female',
    languages: ['English', 'Hindi'],
    mobileNo: '9876543210',
    emailId: 'aditi@example.com',
    type: 'Cook',
    organization: 'ASBL',
    joinedOn: '2022-01-15'
  },
  {
    id: 2,
    name: 'Rajesh Verma',
    role: 'Driver',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    employeeCode: 'D001',
    gender: 'Male',
    languages: ['Hindi', 'Telugu'],
    mobileNo: '9123456780',
    emailId: 'rajesh@example.com',
    type: 'Driver',
    organization: 'ASBL',
    joinedOn: '2023-03-10'
  },
  {
    id: 4,
    name: 'Aditi Sharma',
    role: 'Cook',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    employeeCode: 'C001',
    gender: 'Female',
    languages: ['English', 'Hindi'],
    mobileNo: '9876543210',
    emailId: 'aditi@example.com',
    type: 'Cook',
    organization: 'ASBL',
    joinedOn: '2022-01-15'
  },
  {
    id: 3,
    name: 'Rajesh Verma',
    role: 'Driver',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    employeeCode: 'D001',
    gender: 'Male',
    languages: ['Hindi', 'Telugu'],
    mobileNo: '9123456780',
    emailId: 'rajesh@example.com',
    type: 'Driver',
    organization: 'ASBL',
    joinedOn: '2023-03-10'
  },{
    id: 5,
    name: 'Aditi Sharma',
    role: 'Cook',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    employeeCode: 'C001',
    gender: 'Female',
    languages: ['English', 'Hindi'],
    mobileNo: '9876543210',
    emailId: 'aditi@example.com',
    type: 'Cook',
    organization: 'ASBL',
    joinedOn: '2022-01-15'
  },
  {
    id: 6,
    name: 'Rajesh Verma',
    role: 'Driver',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    employeeCode: 'D001',
    gender: 'Male',
    languages: ['Hindi', 'Telugu'],
    mobileNo: '9123456780',
    emailId: 'rajesh@example.com',
    type: 'Driver',
    organization: 'ASBL',
    joinedOn: '2023-03-10'
  },
];